/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package validator;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testDoubles() {
        assertTrue("isDouble 20.2 should return 'true'", Validator.isDouble("20.2"));
        assertTrue("isDouble 20 should return 'true'", Validator.isDouble("20"));
        assertFalse("isDouble 20n should return 'false'", Validator.isDouble("20n"));
        assertFalse("isDouble defrglk should return 'false'", Validator.isDouble("defrglk"));
    }

    @Test public void testNumeric() {
        assertTrue("isNumeric should return 'true'", Validator.isNumeric("20.2"));
        assertTrue("isNumeric should return 'true'", Validator.isNumeric("20"));
        assertFalse("isNumeric should return 'false'", Validator.isNumeric("20d"));
        assertFalse("isNumeric should return 'false'", Validator.isNumeric("detrtre"));
    }

    @Test public void testValidatorValidateFunction() {

        // Types
        assertTrue("numeric 20 should be 'true'", Validator.validate("20", "numeric"));
        assertTrue("double 20 should be 'true", Validator.validate("20", "double"));

        // Max
        assertTrue("-2 max:20 should be 'true'", Validator.validate("-2", "numeric|max:20"));
        assertTrue("20 max:20 should be 'true'", Validator.validate("20", "numeric|max:20"));
        assertFalse("21 max:20 should be 'false'", Validator.validate("40", "numeric|max:20"));

        // Min
        assertFalse("-20 min:20 should be 'false'", Validator.validate("-20", "numeric|min:20"));
        assertTrue("20 min:20 should be 'false'", Validator.validate("20", "numeric|min:20"));
        assertTrue("21 min:20 should be 'false'", Validator.validate("21", "numeric|min:20"));

        // Required
        assertFalse("'' required should be 'false'", Validator.validate("", "required"));
        assertFalse("null required should be 'false'", Validator.validate(null, "required"));
        assertTrue("TOTO required should be 'false'", Validator.validate("TOTO", "required"));
        assertTrue("12 required numeric should be 'false'", Validator.validate("12", "required|numeric|max:20"));
    }
}
